[workspace]
resolver = "2"
edition = "2021"
workspsace.package.authors = ["Evgeney Knyazhev (SarK0Y) <sark0y@protonmail.com>"]
workspace.package.license-file = "LICENSE"
readme = "README.md"
members = [
    "main",
    "ext/goto"
]
[workspace.dependencies]
##sark0y_tam_rst = {path = "./"}
goto = {path = "./ext/goto"}
