[package]
name ="min_err_per_step"
edition = "2021"
version = "0.0.6"
#publish = true
authors = ["Evgeney Knyazhev (SarK0Y) <sark0y@protonmail.com>"]
license-file = "LICENSE"
#readme = "README.md"
repository = "https://github.com/SarK0Y/TAM_RUSTy/tree/pre-workable/ext/min_err_per_step"
categories = ["rust-patterns", "algorithms"]
kwywords = ["math", "basic", "fast", "kiss"]
description = "Dear User, it's math lib for Rust to calc basic funcs w/ minimal error per step [kiss principle been at the very heart]."
[workspace]
[build-dependencies]
#for_build_rs = { version = "0.0.109", optional = true, default-features = false }
#for_build_rs = { path = "../for_build_rs", version = "0.0.110", optional = true, default-features = false }
[dependencies]
#for_build_rs = { path = "../for_build_rs", version = "0.0.109", optional = true, default-features = false }
once_cell = "1.18.0"
substring = "1.4.5"
num-traits = "0.2.17"
rug = {version = "1.25.0", features = ["integer", "float", "std"]}
Mademoiselle_Entropia = {path = "/tst/mae", version = "1.11.12"}
[lib]
name = "min_err_per_step"
path = "src/lib.rs"
