[package]
name ="goto1717"
edition = "2021"
version = "0.0.147"
publish = true
license-file = "LICENSE"
readme = "README.md"
description = "goto & more for Rust"
[dependencies]
syn = { version = "2.0.0", features = ["full", "extra-traits"] }
quote = "1.0.0"
proc-macro2 = "1.0.0"
once_cell = "1.18.0"
substring = "1.4.5"
rst_lex = { path = "../rst_lex", version = "0.0.90", optional = true }
Mademoiselle_Entropia = {path = "/tst/mae", version = "1.11.12"}
[features]
default = ["stable"]
tst = ["rst_lex/dev_hell_n_fun"]
stable = ["rst_lex/stable"]
[lib]
proc-macro = true
