[package]
name ="goto1717"
edition = "2021"
version = "0.0.40"
publish = true
license-file = "LICENSE"
description = "goto & more for Rust"
[dependencies]
syn = { version = "2.0.0", features = ["full", "extra-traits"] }
quote = "1.0.0"
proc-macro2 = "1.0.0"
once_cell = "1.18.0"
substring = "1.4.5"
Mademoiselle_Entropia = {path = "/tst/mae", version = "1.11.12"}
[lib]
proc-macro = true
